# Generated by Django 4.0.4 on 2022-06-28 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='task_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='todos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
